CS2103-AY1819S1-T09-2/main

src/main/java/seedu/address/model/Anakin_Model.java, src/main/java/seedu/address/model/Anakin_ReadOnlyAnakin.java
Hopefully enough to get started. It's assumed that like `Person`, `Anakin_Deck` and `Anakin_Card` are immutable.
=> Skeletal Anakin Model

src/main/java/seedu/address/commons/core/Anakin_ComponentManager.java, src/main/java/seedu/address/commons/events/model/Anakin_AnakinChangedEvent.java, src/main/java/seedu/address/logic/Anakin_commands/Anakin_Command.java, src/main/java/seedu/address/logic/Anakin_commands/Anakin_DelDeckCommand.java, src/main/java/seedu/address/logic/Anakin_commands/Anakin_NewDeckCommand.java, src/main/java/seedu/address/model/Anakin.java, src/main/java/seedu/address/model/Anakin_ModelManager.java, src/main/java/seedu/address/model/Anakin_VersionedAnakin.java, src/main/java/seedu/address/model/Anakin_deck/Anakin_Card.java
Add 8 new classes: Anakin_Command, Anakin_NewDeckCommand, Anakin_DelDeckCommand, Anakin_ComponentManager, Anakin_AnakinChangedEvent, Anakin, Anakin_ModelManager, Anakin_VersionedAnakin
Modify Anakin_Card class
=> Add 8 new classes

src/test/java/seedu/address/ui/PersonListPanelTest.java
See nus-cs2103-AY1819S1/forum#53
=> Fix upstream bug

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/Anakin_commands/AnakinEditCardCommand.java, src/main/java/seedu/address/model/Anakin_Model.java, src/main/java/seedu/address/model/Anakin_ModelManager.java, src/main/java/seedu/address/model/Anakin_deck/AnakinAnswer.java, src/main/java/seedu/address/model/Anakin_deck/AnakinQuestion.java, src/main/java/seedu/address/model/Anakin_deck/Anakin_Card.java
To add `editcard`, I had to first implement the following changes:
- Add `Question` and `Answer` classes and update `Anakin_Card`
- Add card-related methods to `Anakin_Model`
- Update predefined Messages with `Invalid Card Displayed` message
=> Add Edit Card Command

src/main/java/seedu/address/logic/AnakinCommands/AnakinNewCardCommand.java, src/main/java/seedu/address/logic/AnakinParser/AnakinNewCardCommandParser.java, src/main/java/seedu/address/logic/AnakinParser/AnakinParser.java, src/main/java/seedu/address/logic/AnakinParser/AnakinParserUtil.java, src/main/java/seedu/address/model/anakindeck/AnakinCard.java
=> Added support for card creation

src/main/java/seedu/address/logic/AnakinCommands/AnakinDelCardCommand.java, src/main/java/seedu/address/logic/AnakinParser/AnakinDelCardCommandParser.java, src/main/java/seedu/address/logic/AnakinParser/AnakinParser.java
=> Add logic for card deletion

src/main/java/seedu/address/logic/AnakinCommands/AnakinEditCardCommand.java, src/main/java/seedu/address/logic/AnakinParser/AnakinEditCardCommandParser.java, src/main/java/seedu/address/logic/AnakinParser/AnakinParser.java
=> Add edit command parser

_reposense/config.json
=> Add reposense config.json

README.adoc, docs/UserGuide.adoc
Fix broken links
Add "user reviews"
=> Update README and UserGuide

src/test/java/seedu/address/logic/commands/AnakinNewDeckCommandTest.java, src/test/java/seedu/address/testutil/AnakinDeckBuilder.java
=> Add unit test for AnakinNewDeckCommand. Create AnakinDeckBuilder.java

src/main/java/seedu/address/storage/AnakinAnakinStorage.java, src/main/java/seedu/address/storage/AnakinStorage.java, src/main/java/seedu/address/storage/AnakinStorageManager.java
=> Morph Storage Component

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/AnakinCommands/AnakinDelDeckCommand.java, src/main/java/seedu/address/model/anakindeck/AnakinDeckNameContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/AnakinCommandTestUtil.java, src/test/java/seedu/address/logic/commands/AnakinDelDeckCommandTest.java, src/test/java/seedu/address/testutil/AnakinTestUtil.java, src/test/java/seedu/address/testutil/AnakinTypicalDecks.java, src/test/java/seedu/address/testutil/AnakinTypicalIndexes.java
Add 2 AnakinDelDeckCommandTest.java and AnakinTestUtil.java
=> Add AnakinDelDeckCommand unit test

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/anakincommands/AnakinCdCommand.java, src/main/java/seedu/address/model/Anakin.java, src/main/java/seedu/address/model/AnakinModel.java, src/main/java/seedu/address/model/AnakinModelManager.java, src/test/java/seedu/address/logic/commands/AnakinCdCommandTest.java, src/test/java/seedu/address/logic/commands/AnakinNewDeckCommandTest.java
=> Add cdCommand test

_reposense/config.json
again because reposense isn't detecting my code properly :(
=> Update reposense config

src/main/java/seedu/address/logic/anakincommands/AnakinRedoCommand.java, src/main/java/seedu/address/logic/anakincommands/AnakinUndoCommand.java, src/test/java/seedu/address/logic/commands/AnakinRedoCommandTest.java, src/test/java/seedu/address/logic/commands/AnakinUndoCommandTest.java
=> Add Undo and Redo commands

src/main/java/seedu/address/logic/anakincommands/AnakinCdCommand.java
Accept "cd .." instead of "cd.." for navigating out of deck
=> Fix CdCommand

src/main/java/seedu/address/model/Anakin.java, src/main/java/seedu/address/model/AnakinReadOnlyAnakin.java, src/test/java/seedu/address/TestApp.java, src/test/java/seedu/address/logic/commands/AnakinDelCardCommandTest.java, src/test/java/seedu/address/logic/commands/AnakinNewCardCommandTest.java, src/test/java/seedu/address/model/AnakinTest.java, src/test/java/seedu/address/testutil/AnakinTypicalDecks.java, src/test/java/seedu/address/testutil/AnakinTypicalIndexes.java
Unit tests for NewCardCommand, DelCardCommand.
=> Card Create/Delete unit tests

src/test/java/seedu/address/logic/commands/AnakinCommandTestUtil.java, src/test/java/seedu/address/logic/parser/AnakinCdCommandParserTest.java, src/test/java/seedu/address/logic/parser/AnakinCommandParserTestUtil.java, src/test/java/seedu/address/logic/parser/AnakinDelCardCommandParserTest.java, src/test/java/seedu/address/logic/parser/AnakinDelDeckCommandParserTest.java, src/test/java/seedu/address/logic/parser/AnakinEditCardParserTest.java, src/test/java/seedu/address/logic/parser/AnakinEditDeckParserTest.java, src/test/java/seedu/address/logic/parser/AnakinNewCardCommandParserTest.java, src/test/java/seedu/address/logic/parser/AnakinNewDeckCommandParserTest.java, src/test/java/seedu/address/testutil/EditCardDescriptorBuilder.java, src/test/java/seedu/address/testutil/EditDeckDescriptorBuilder.java
Also create supporting files including DescriptorBuilders and CommandUtils
=> Add 7 CommandParser tests

src/test/java/seedu/address/logic/commands/AnakinCommandTestUtil.java, src/test/java/seedu/address/logic/commands/AnakinEditCardCommandTest.java
=> Add EditCardCommand test

src/main/java/seedu/address/logic/commands/EditDeckCommand.java, src/test/java/seedu/address/logic/commands/EditCardCommandTest.java, src/test/java/seedu/address/logic/commands/EditDeckCommandTest.java, src/test/java/seedu/address/logic/parser/EditDeckParserTest.java, src/test/java/systemtests/ErrorDialogGuiTest.java
Let us revive travis with this PR.
=> Fix EditCardTests, EditDeckParserTest and GUITest

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/deck/CardQuestionContainsKeywordsPredicate.java, src/test/data/XmlSerializableAnakinTest/typicalDecksAnakin.xml, src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/NewCardCommandTest.java, src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java, src/test/java/seedu/address/testutil/TypicalCards.java, src/test/java/seedu/address/testutil/TypicalDecks.java
Implement FindCommand
Update UserGuide, DeveloperGuide 
Add implementation details of the card list
Implement tests for FindCommand, add more fields to TypicalCards and TypicalDecks 
Update typicalDecksAnakin.xml
Refactor `goIntoDeck` to `getIntoDeck` in ModelManager
=>  Add FindCommand and tests

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/ClassifyCommand.java, src/main/java/seedu/address/logic/parser/ClassifyCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/Anakin.java, src/main/java/seedu/address/model/deck/Card.java, src/main/java/seedu/address/model/deck/Performance.java
=> Performance tracking - Add classify command and related utils

docs/AboutUs.adoc, docs/DeveloperGuide.adoc, docs/UserGuide.adoc, docs/team/truongthanh2606.adoc, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCardCommand.java, src/main/java/seedu/address/logic/commands/DeleteDeckCommand.java, src/main/java/seedu/address/logic/commands/EditCardCommand.java, src/main/java/seedu/address/logic/commands/EditDeckCommand.java, src/main/java/seedu/address/logic/commands/ExportDeckCommand.java, src/main/java/seedu/address/logic/commands/ImportDeckCommand.java, src/main/java/seedu/address/logic/commands/NewCardCommand.java, src/main/java/seedu/address/logic/commands/NewDeckCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/deck/CardQuestionContainsKeywordsPredicate.java, src/main/java/seedu/address/model/deck/DeckNameContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java, src/test/java/seedu/address/logic/commands/NewCardCommandTest.java, src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
Block card-level operations while user is not inside any decks
Block deck-level operations while user is inside a deck
Update project portfolio
Update user guide, developer guide
=>  Modify card and deck-level commands, update userguide, developerguide

src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java, src/main/java/seedu/address/logic/commands/DeleteCardCommand.java, src/main/java/seedu/address/logic/commands/DeleteDeckCommand.java, src/main/java/seedu/address/logic/commands/EditCardCommand.java, src/main/java/seedu/address/logic/commands/EditDeckCommand.java, src/main/java/seedu/address/logic/commands/ExportDeckCommand.java, src/main/java/seedu/address/logic/commands/NewCardCommand.java, src/main/java/seedu/address/logic/commands/ReviewCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/model/Anakin.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyAnakin.java, src/main/java/seedu/address/model/deck/UniqueCardList.java, src/main/java/seedu/address/model/deck/UniqueDeckList.java, src/test/data/PortManagerTest/Valid Exported Deck.xml, src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCardCommandTest.java, src/test/java/seedu/address/logic/commands/EditCardCommandTest.java, src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/commands/NewCardCommandTest.java, src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java, src/test/java/seedu/address/model/AnakinTest.java
Command exception is now checked in Logic component (in the Command class itself) instead of being checked in Model component.
This reduce the possible bugs but increase coupling between Logic and Model component
=> Change the logic of executing commands

docs/UserGuide.adoc, docs/team/truongthanh2606.adoc
Update User Guide
Update project portfolio
=> Resolve issues #211, #212, #213, #214, #217

docs/UserGuide.adoc, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Add LogicManagerTest

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/NewCardCommand.java
This pull request attempts to fix #210 #215  #220 #223  #229 #231
=> Update userguide on multiple arguments and import format

docs/team/truongthanh2606.adoc, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/model/Anakin.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyAnakin.java, src/main/java/seedu/address/model/VersionedAnakin.java, src/main/java/seedu/address/model/deck/Card.java, src/main/java/seedu/address/model/deck/Deck.java, src/main/java/seedu/address/model/deck/UniqueCardList.java, src/main/java/seedu/address/model/deck/UniqueDeckList.java, src/test/data/PortManagerTest/Valid Exported Deck.xml, src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java, src/test/java/seedu/address/logic/commands/EditCardCommandTest.java, src/test/java/seedu/address/logic/commands/EditDeckCommandTest.java, src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java, src/test/java/seedu/address/logic/commands/NewCardCommandTest.java, src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java, src/test/java/seedu/address/logic/commands/RedoCommandTest.java, src/test/java/systemtests/ClearCommandSystemTest.java
Create a deep copy of Anakin for each state instead of a shallow copy.
`cd` and `cd ..` are now undoable, they will commit Anakin.
=> Update message for `redo`, resolve issue #219

docs/team/johndoe.adoc, src/main/java/seedu/address/logic/commands/ClassifyCommand.java, src/main/java/seedu/address/logic/parser/ChangeDeckCommandParser.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/ClassifyCardParserTest.java, src/test/java/seedu/address/logic/parser/ParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/logic/parser/ReviewCommandParserTest.java
Add several Parser and Command tests.
=> Add Parser integration test and Several Parser unit tests

docs/UserGuide.adoc, docs/team/tomforge.adoc, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/parser/ListCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/main/java/seedu/address/model/deck/CardPerformanceMatchesPerformancesPredicate.java, src/main/java/seedu/address/model/deck/Performance.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/model/deck/CardPerformanceMatchesPerformancesTest.java, src/test/java/seedu/address/model/deck/PerformanceTest.java, src/test/java/seedu/address/testutil/TypicalCards.java
=> Add ability to filter by card difficulty with list command (WIP - pending docs)
